interface Window {
    restoreThinkingState?: () => void;
    resumePendingAIRequest?: () => void;
    TRPG?: TrpgNamespace;
    TrpgApi: TrpgApiClient;
    TrpgDom: TrpgDomClient;
    TrpgTemplates: TrpgTemplateRenderer;
    ScenarioModel: ScenarioModelConstructor;
    ScenarioView: ScenarioViewConstructor;
    ScenarioController: { new(): unknown };
    DiceTool: DiceToolConstructor;
    CheckTool: CheckToolConstructor;
    ToolManager: ToolManagerConstructor;
    toolManager?: ToolManager;
    currentRoom?: Room | null;
    uploadedCoverFile?: File;
    currentPlatform?: string;
    currentTestingPlatform?: string;
    loadAIRoles?: () => void;
    reloadRoleConfigs?: () => Promise<void>;
    showNotification?: (message: string, type?: string) => void;
    recordCharacterChange?: (payload: Record<string, unknown>) => Promise<unknown>;
    TrpgCookies?: TrpgCookieClient;
    configManager: ConfigManager;
    aiPlatformManager: AIPlatformManager;
    testRequestConfigs: Record<string, TestRequestConfig>;
    getTestRequestConfig(modelId: string): TestRequestConfig;
    marked?: MarkedParser;
    renderChatMessages?: (messages: ChatMessage[]) => void;
    getCurrentChatMessages?: () => ChatMessage[];
    clearChatMessages?: () => void;
    setChatReadOnly?: (readOnly: boolean) => void;
    joinSocketRoom?: (roomId: string) => void;
    leaveSocketRoom?: (roomId: string) => void;
    reconnectSocket?: () => void;
    disconnectSocket?: () => void;
    initRoomManagement?: () => void;
    loadRoomsList?: () => Promise<void>;
    autoLoadLastRoom?: () => Promise<void>;
    clearCurrentRoom?: () => void;
    clearCharacterManagement?: () => void;
    reloadCharacterManagement?: () => Promise<void>;
    switchMainTab?: (tabId: string, options?: { clearNav?: boolean }) => void;
    refreshAdminNavigation?: () => void;
    refreshScenarioManagement?: () => void;
    openCreateRoomWithScenario?: (scenarioId: number) => Promise<void>;
}

declare function showNotification(message: string, type?: string): void;
declare function showAuthModal(): void;
declare const TrpgCookies: TrpgCookieClient;
declare function initAuth(): Promise<boolean>;
declare const TrpgApi: TrpgApiClient;
declare const TrpgDom: TrpgDomClient;
